inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4.5
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact