development: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://localhost:5432/todo_develop?pool=50') %>

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://localhost:5432/todo_test') %>

production:
  <<: *default
